#prints the list of students
puts "The students of Villains Academy"
puts "--------------"
puts "Dr . Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
#next lets print the total number of students
puts "Overall, we have 11 great students"